name: Deploy to lightning.ai
# TODO(alecmerdler): Replicate for `echo-staging` on every merge to `main` branch
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 35
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.LIGHTNING_UI_SSH_KEY }}
      - name: Install frontend dependencies
        run: cd echo/ui && yarn install
      - name: Build frontend
        run: cd echo/ui && yarn build
        env:
          REACT_APP_ECHO_SOURCE_TYPE_FILE_ENABLED: "false"
          REACT_APP_ECHO_SOURCE_TYPE_RECORDING_ENABLED: "true"
          REACT_APP_ECHO_SOURCE_TYPE_YOUTUBE_ENABLED: "true"
          REACT_APP_ECHO_GARBAGE_COLLECTION_MAX_AGE_SECONDS: 84600
          REACT_APP_ECHO_SENTRY_DSN: ${{ secrets.ECHO_SENTRY_DSN }}
      - name: Upload frontend build
        uses: actions/upload-artifact@v1
        with:
          name: echo-frontend-build
          path: echo/ui/build
  deploy:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Python dependencies
        run: |
          pip --version
          pip install -r requirements.txt --quiet
          pip list
        shell: bash
      - name: Retrieve frontend build
        uses: actions/download-artifact@v1
        with:
          name: echo-frontend-build
          path: echo/ui/build
      - name: Deploy
        env:
          LIGHTNING_USER_ID: ${{ secrets.LIGHTNING_USER_ID }}
          LIGHTNING_API_KEY: ${{ secrets.LIGHTNING_API_KEY }}
          LIGHTNING_CLOUD_PROJECT_ID: ${{ secrets.LIGHTNING_CLOUD_PROJECT_ID }}
        run: |
          lightning run app app.py \
            --cloud \
            --name "echo-prod" \
            --open-ui false \
            --env ECHO_MODE=production \
            --env ECHO_MODEL_SIZE=base \
            --env ECHO_ENABLE_MULTI_TENANCY=true \
            --env ECHO_RECOGNIZER_MIN_REPLICAS=1 \
            --env ECHO_RECOGNIZER_MAX_IDLE_SECONDS_PER_WORK=120 \
            --env ECHO_RECOGNIZER_MAX_PENDING_CALLS_PER_WORK=10 \
            --env ECHO_RECOGNIZER_AUTOSCALER_CRON_SCHEDULE_DEFAULT="*/5 * * * *" \
            --env ECHO_RECOGNIZER_CLOUD_COMPUTE=gpu \
            --env ECHO_YOUTUBER_MIN_REPLICAS=1 \
            --env ECHO_YOUTUBER_MAX_IDLE_SECONDS_PER_WORK=120 \
            --env ECHO_YOUTUBER_MAX_PENDING_CALLS_PER_WORK=10 \
            --env ECHO_YOUTUBER_AUTOSCALER_CRON_SCHEDULE_DEFAULT="*/5 * * * *" \
            --env ECHO_YOUTUBER_CLOUD_COMPUTE=cpu \
            --env ECHO_USER_ECHOES_LIMIT=3 \
            --env ECHO_SOURCE_TYPE_FILE_ENABLED=false \
            --env ECHO_SOURCE_TYPE_RECORDING_ENABLED=true \
            --env ECHO_SOURCE_TYPE_YOUTUBE_ENABLED=true \
            --env ECHO_GARBAGE_COLLECTION_CRON_SCHEDULE="*/30 * * * *" \
            --env ECHO_GARBAGE_COLLECTION_MAX_AGE_SECONDS=86400 \
            --env ECHO_SENTRY_DSN=${{ secrets.ECHO_SENTRY_DSN }} \
            --env ECHO_VIDEO_SOURCE_MAX_DURATION_SECONDS=900 \
        shell: bash
