name: Python Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macOS-10.15]
        python-version: ["3.10"]
    timeout-minutes: 35
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup macOS
        if: runner.os == 'macOS'
        run: |
          brew install libomp  # https://github.com/pytorch/pytorch/issues/20030
      - name: Get pip cache
        id: pip-cache
        run: |
          python -c "from pip._internal.locations import USER_CACHE_DIR; print('::set-output name=dir::' + USER_CACHE_DIR)"
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-py${{ matrix.python-version }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-py${{ matrix.python-version }}-
      - name: Install dependencies
        run: |
          python --version
          pip --version
          pip install -r requirements.txt --upgrade --quiet
          pip install -r tests/requirements.txt --quiet
          pip list
        shell: bash
      - name: Run Tests
        run: |
          coverage run --source echo -m py.test echo tests -v --junitxml=junit/test-results-${{ runner.os }}-${{ matrix.python-version }}.xml
      - name: Statistics
        if: success()
        run: |
          coverage report
